{"testcasedatas":[{"firstjacocotime":49.51,"tagname":"11","firstexecutionsuccess":false,"firsttestcasepath":"\\testcase\\interestcases\\testcase12_1_021.py","firstconsumedtime":113.889,"firstlocpath":"\\exeresult\\interestresult\\12_1_021.txt","firstcoveragepath":"\\coverage\\interestcoverage\\coverage12_1_021.ec","firsterrorlog":"FAILstr(e):\t\t'NoneType' object has no attribute 'click'repr(e):\tAttributeError(\"'NoneType' object has no attribute 'click'\",)Traceback (most recent call last):  File \"\\testcase\\interestcases\\testcase12_1_021.py\", line 111, in <module>    scrollToFindElement(driver, \"new UiSelector().text(\\\"Swipe back to list\\\")\").click()AttributeError: 'NoneType' object has no attribute 'click'FAILstr(e):\t\tMessage: An element could not be located on the page using the given search parameters.repr(e):\tNoSuchElementException()Traceback (most recent call last):  File \"\\testcase\\interestcases\\testcase12_1_021.py\", line 143, in <module>    element = getElememt(driver, \"new UiSelector().resourceId(\\\"io.dwak.holohackernews.app:id\/action_1\\\").className(\\\"android.widget.Button\\\")\")  File \"\\testcase\\interestcases\\testcase12_1_021.py\", line 34, in getElememt    element = driver.find_element_by_android_uiautomator(str)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 327, in find_element_by_android_uiautomator    return self.find_element(by=By.ANDROID_UIAUTOMATOR, value=uia_string)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 219, in find_element    'value': value})['value']  File \"C:\\Python27\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute    self.error_handler.check_response(response)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 29, in check_response    raise wdeNoSuchElementException: Message: An element could not be located on the page using the given search parameters."},{"firstjacocotime":58.44,"tagname":"12","firstexecutionsuccess":true,"firsttestcasepath":"\\testcase\\interestcases\\testcase13_1_021.py","firstconsumedtime":19.843,"firstlocpath":"\\exeresult\\interestresult\\13_1_021.txt","firstcoveragepath":"\\coverage\\interestcoverage\\coverage13_1_021.ec","firsterrorlog":null},{"firstjacocotime":30.185999,"tagname":"13","firstexecutionsuccess":false,"firsttestcasepath":"\\testcase\\interestcases\\testcase14_5_000.py","firstconsumedtime":138.301,"firstlocpath":"\\exeresult\\interestresult\\14_5_000.txt","firstcoveragepath":"\\coverage\\interestcoverage\\coverage14_5_000.ec","firsterrorlog":"FAILstr(e):\t\tMessage: An element could not be located on the page using the given search parameters.repr(e):\tNoSuchElementException()Traceback (most recent call last):  File \"\\testcase\\interestcases\\testcase14_5_000.py\", line 172, in <module>    element = getElememtBack(driver, \"new UiSelector().text(\\\"Large\\\")\", \"new UiSelector().className(\\\"android.widget.CheckedTextView\\\").instance(2)\")  File \"\\testcase\\interestcases\\testcase14_5_000.py\", line 53, in getElememtBack    element = driver.find_element_by_android_uiautomator(str2)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 327, in find_element_by_android_uiautomator    return self.find_element(by=By.ANDROID_UIAUTOMATOR, value=uia_string)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 219, in find_element    'value': value})['value']  File \"C:\\Python27\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute    self.error_handler.check_response(response)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 29, in check_response    raise wdeNoSuchElementException: Message: An element could not be located on the page using the given search parameters."},{"firstjacocotime":5.002,"tagname":"preference_pre_reverse","firstexecutionsuccess":true,"firsttestcasepath":"\\testcase\\allpreferencecases\\precase_log.py","firstconsumedtime":31.346,"firstlocpath":"\\exeresult\\interestresult\\preference_pre_reverse.txt","firstcoveragepath":"\\coverage\\interestallcoverage\\coveragepreference_pre_reverse.ec","firsterrorlog":null},{"firstjacocotime":5.0039997,"tagname":"preference_pre_default","firstexecutionsuccess":true,"firsttestcasepath":"\\testcase\\allpreferencecases\\defaultprecase_log.py","firstconsumedtime":28.299,"firstlocpath":"\\exeresult\\interestresult\\preference_pre_default.txt","firstcoveragepath":"\\coverage\\interestallcoverage\\coveragepreference_pre_default.ec","firsterrorlog":null},{"firstjacocotime":8.101999,"tagname":"0","firstexecutionsuccess":false,"firsttestcasepath":"\\testcase\\interestcases\\testcase1_1_021.py","firstconsumedtime":45.545998,"firstlocpath":"\\exeresult\\interestresult\\1_1_021.txt","firstcoveragepath":"\\coverage\\interestcoverage\\coverage1_1_021.ec","firsterrorlog":"FAILstr(e):\t\tMessage: An unknown server-side error occurred while processing the command. Original error: The swipe did not complete successfullyrepr(e):\tWebDriverException()Traceback (most recent call last):  File \"\\testcase\\interestcases\\testcase1_1_021.py\", line 111, in <module>    scrollToFindElement(driver, \"new UiSelector().text(\\\"Swipe back to list\\\")\").click()  File \"\\testcase\\interestcases\\testcase1_1_021.py\", line 79, in scrollToFindElement    swipe(driver, 0.5, 0.55, 0.5, 0.2)  File \"\\testcase\\interestcases\\testcase1_1_021.py\", line 65, in swipe    end_y=int(height * endyper), duration=2000)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 548, in swipe    action.perform()  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\common\\touch_action.py\", line 96, in perform    self._driver.execute(Command.TOUCH_ACTION, params)  File \"C:\\Python27\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute    self.error_handler.check_response(response)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 29, in check_response    raise wdeWebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The swipe did not complete successfullyFAILstr(e):\t\tMessage: An element could not be located on the page using the given search parameters.repr(e):\tNoSuchElementException()Traceback (most recent call last):  File \"\\testcase\\interestcases\\testcase1_1_021.py\", line 138, in <module>    element = getElememtBack(driver, \"new UiSelector().text(\\\"2 pavlov\\\")\", \"new UiSelector().className(\\\"android.widget.TextView\\\").instance(13)\")  File \"\\testcase\\interestcases\\testcase1_1_021.py\", line 53, in getElememtBack    element = driver.find_element_by_android_uiautomator(str2)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 327, in find_element_by_android_uiautomator    return self.find_element(by=By.ANDROID_UIAUTOMATOR, value=uia_string)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 219, in find_element    'value': value})['value']  File \"C:\\Python27\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute    self.error_handler.check_response(response)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 29, in check_response    raise wdeNoSuchElementException: Message: An element could not be located on the page using the given search parameters."},{"firstjacocotime":6.62,"tagname":"1","firstexecutionsuccess":false,"firsttestcasepath":"\\testcase\\interestcases\\testcase2_2_013.py","firstconsumedtime":41.927002,"firstlocpath":"\\exeresult\\interestresult\\2_2_013.txt","firstcoveragepath":"\\coverage\\interestcoverage\\coverage2_2_013.ec","firsterrorlog":"FAILstr(e):\t\tMessage: An unknown server-side error occurred while processing the command. Original error: The swipe did not complete successfullyrepr(e):\tWebDriverException()Traceback (most recent call last):  File \"\\testcase\\interestcases\\testcase2_2_013.py\", line 111, in <module>    scrollToFindElement(driver, \"new UiSelector().text(\\\"Swipe back to list\\\")\").click()  File \"\\testcase\\interestcases\\testcase2_2_013.py\", line 79, in scrollToFindElement    swipe(driver, 0.5, 0.55, 0.5, 0.2)  File \"\\testcase\\interestcases\\testcase2_2_013.py\", line 65, in swipe    end_y=int(height * endyper), duration=2000)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 548, in swipe    action.perform()  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\common\\touch_action.py\", line 96, in perform    self._driver.execute(Command.TOUCH_ACTION, params)  File \"C:\\Python27\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute    self.error_handler.check_response(response)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 29, in check_response    raise wdeWebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The swipe did not complete successfullyFAILstr(e):\t\tMessage: An element could not be located on the page using the given search parameters.repr(e):\tNoSuchElementException()Traceback (most recent call last):  File \"\\testcase\\interestcases\\testcase2_2_013.py\", line 138, in <module>    element = getElememtBack(driver, \"new UiSelector().text(\\\"The note about the Brunswick Centre is interesting. This odd space-age utopian building was in much worse shape until a Â£20M renovation in 2006, with The Guardian characterizing it as one of the \u201Cmost miserable places in London\u201D: https:\/\/www.google.co.uk\/amp\/s\/amp.theguardian.com\/artanddes...In that article, the architect mentions he originally wanted it built out of brick in the style of Alvar Aalto, but they had to settle for painted concrete. In 1970 even the paint job was cut from the budget and wasn\u2019t done until the renovation, so for 36 years the Brunswick was a brutalist bunker.Im glad they fixed it. It\u2019s an interesting landmark of British modernism\u2019s fling with low-key sci-fi architecture \u2014 and the grocery store is good, I go there all the time.\\\")\", \"new UiSelector().className(\\\"android.widget.TextView\\\").instance(16)\")  File \"\\testcase\\interestcases\\testcase2_2_013.py\", line 53, in getElememtBack    element = driver.find_element_by_android_uiautomator(str2)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 327, in find_element_by_android_uiautomator    return self.find_element(by=By.ANDROID_UIAUTOMATOR, value=uia_string)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 219, in find_element    'value': value})['value']  File \"C:\\Python27\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute    self.error_handler.check_response(response)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 29, in check_response    raise wdeNoSuchElementException: Message: An element could not be located on the page using the given search parameters."},{"firstjacocotime":55.222,"tagname":"2","firstexecutionsuccess":false,"firsttestcasepath":"\\testcase\\interestcases\\testcase3_5_000.py","firstconsumedtime":51.804,"firstlocpath":"\\exeresult\\interestresult\\3_5_000.txt","firstcoveragepath":"\\coverage\\interestcoverage\\coverage3_5_000.ec","firsterrorlog":"FAILstr(e):\t\t'NoneType' object has no attribute 'click'repr(e):\tAttributeError(\"'NoneType' object has no attribute 'click'\",)Traceback (most recent call last):  File \"\\testcase\\interestcases\\testcase3_5_000.py\", line 111, in <module>    scrollToFindElement(driver, \"new UiSelector().text(\\\"Comment Text size\\\")\").click()AttributeError: 'NoneType' object has no attribute 'click'FAILstr(e):\t\tMessage: UiSelector[CLASS=android.widget.TextView, RESOURCE_ID=io.dwak.holohackernews.app:id\/action_open_browser]repr(e):\tNoSuchElementException()Traceback (most recent call last):  File \"\\testcase\\interestcases\\testcase3_5_000.py\", line 137, in <module>    TouchAction(driver).long_press(element).release().perform()  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\common\\touch_action.py\", line 96, in perform    self._driver.execute(Command.TOUCH_ACTION, params)  File \"C:\\Python27\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute    self.error_handler.check_response(response)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 29, in check_response    raise wdeNoSuchElementException: Message: UiSelector[CLASS=android.widget.TextView, RESOURCE_ID=io.dwak.holohackernews.app:id\/action_open_browser]"},{"firstjacocotime":15.029,"tagname":"3","firstexecutionsuccess":false,"firsttestcasepath":"\\testcase\\interestcases\\testcase4_1_021.py","firstconsumedtime":68.001,"firstlocpath":"\\exeresult\\interestresult\\4_1_021.txt","firstcoveragepath":"\\coverage\\interestcoverage\\coverage4_1_021.ec","firsterrorlog":"FAILstr(e):\t\tMessage: An unknown server-side error occurred while processing the command. Original error: The swipe did not complete successfullyrepr(e):\tWebDriverException()Traceback (most recent call last):  File \"\\testcase\\interestcases\\testcase4_1_021.py\", line 111, in <module>    scrollToFindElement(driver, \"new UiSelector().text(\\\"Swipe back to list\\\")\").click()  File \"\\testcase\\interestcases\\testcase4_1_021.py\", line 79, in scrollToFindElement    swipe(driver, 0.5, 0.55, 0.5, 0.2)  File \"\\testcase\\interestcases\\testcase4_1_021.py\", line 65, in swipe    end_y=int(height * endyper), duration=2000)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 548, in swipe    action.perform()  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\common\\touch_action.py\", line 96, in perform    self._driver.execute(Command.TOUCH_ACTION, params)  File \"C:\\Python27\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute    self.error_handler.check_response(response)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 29, in check_response    raise wdeWebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The swipe did not complete successfully"},{"firstjacocotime":19.648998,"tagname":"4","firstexecutionsuccess":true,"firsttestcasepath":"\\testcase\\interestcases\\testcase5_1_021.py","firstconsumedtime":91.812,"firstlocpath":"\\exeresult\\interestresult\\5_1_021.txt","firstcoveragepath":"\\coverage\\interestcoverage\\coverage5_1_021.ec","firsterrorlog":null},{"firstjacocotime":37.668,"tagname":"5","firstexecutionsuccess":false,"firsttestcasepath":"\\testcase\\interestcases\\testcase6_1_021.py","firstconsumedtime":71.193,"firstlocpath":"\\exeresult\\interestresult\\6_1_021.txt","firstcoveragepath":"\\coverage\\interestcoverage\\coverage6_1_021.ec","firsterrorlog":"FAILstr(e):\t\t'NoneType' object has no attribute 'click'repr(e):\tAttributeError(\"'NoneType' object has no attribute 'click'\",)Traceback (most recent call last):  File \"\\testcase\\interestcases\\testcase6_1_021.py\", line 111, in <module>    scrollToFindElement(driver, \"new UiSelector().text(\\\"Swipe back to list\\\")\").click()AttributeError: 'NoneType' object has no attribute 'click'"},{"firstjacocotime":38.159,"tagname":"6","firstexecutionsuccess":true,"firsttestcasepath":"\\testcase\\interestcases\\testcase7_1_021.py","firstconsumedtime":73.449,"firstlocpath":"\\exeresult\\interestresult\\7_1_021.txt","firstcoveragepath":"\\coverage\\interestcoverage\\coverage7_1_021.ec","firsterrorlog":null},{"firstjacocotime":41.392,"tagname":"7","firstexecutionsuccess":false,"firsttestcasepath":"\\testcase\\interestcases\\testcase8_1_021.py","firstconsumedtime":73.989,"firstlocpath":"\\exeresult\\interestresult\\8_1_021.txt","firstcoveragepath":"\\coverage\\interestcoverage\\coverage8_1_021.ec","firsterrorlog":"FAILstr(e):\t\tMessage: An unknown server-side error occurred while processing the command. Original error: The swipe did not complete successfullyrepr(e):\tWebDriverException()Traceback (most recent call last):  File \"\\testcase\\interestcases\\testcase8_1_021.py\", line 111, in <module>    scrollToFindElement(driver, \"new UiSelector().text(\\\"Swipe back to list\\\")\").click()  File \"\\testcase\\interestcases\\testcase8_1_021.py\", line 79, in scrollToFindElement    swipe(driver, 0.5, 0.55, 0.5, 0.2)  File \"\\testcase\\interestcases\\testcase8_1_021.py\", line 65, in swipe    end_y=int(height * endyper), duration=2000)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 548, in swipe    action.perform()  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\common\\touch_action.py\", line 96, in perform    self._driver.execute(Command.TOUCH_ACTION, params)  File \"C:\\Python27\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute    self.error_handler.check_response(response)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 29, in check_response    raise wdeWebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The swipe did not complete successfully"},{"firstjacocotime":53.664997,"tagname":"8","firstexecutionsuccess":true,"firsttestcasepath":"\\testcase\\interestcases\\testcase9_1_021.py","firstconsumedtime":57.592,"firstlocpath":"\\exeresult\\interestresult\\9_1_021.txt","firstcoveragepath":"\\coverage\\interestcoverage\\coverage9_1_021.ec","firsterrorlog":null},{"firstjacocotime":41.669003,"tagname":"9","firstexecutionsuccess":false,"firsttestcasepath":"\\testcase\\interestcases\\testcase10_1_021.py","firstconsumedtime":96.04199,"firstlocpath":"\\exeresult\\interestresult\\10_1_021.txt","firstcoveragepath":"\\coverage\\interestcoverage\\coverage10_1_021.ec","firsterrorlog":"FAILstr(e):\t\tMessage: An unknown server-side error occurred while processing the command. Original error: The swipe did not complete successfullyrepr(e):\tWebDriverException()Traceback (most recent call last):  File \"\\testcase\\interestcases\\testcase10_1_021.py\", line 111, in <module>    scrollToFindElement(driver, \"new UiSelector().text(\\\"Swipe back to list\\\")\").click()  File \"\\testcase\\interestcases\\testcase10_1_021.py\", line 79, in scrollToFindElement    swipe(driver, 0.5, 0.55, 0.5, 0.2)  File \"\\testcase\\interestcases\\testcase10_1_021.py\", line 65, in swipe    end_y=int(height * endyper), duration=2000)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 548, in swipe    action.perform()  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\common\\touch_action.py\", line 96, in perform    self._driver.execute(Command.TOUCH_ACTION, params)  File \"C:\\Python27\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute    self.error_handler.check_response(response)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 29, in check_response    raise wdeWebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The swipe did not complete successfullyFAILstr(e):\t\tMessage: An element could not be located on the page using the given search parameters.repr(e):\tNoSuchElementException()Traceback (most recent call last):  File \"\\testcase\\interestcases\\testcase10_1_021.py\", line 143, in <module>    element = getElememt(driver, \"new UiSelector().resourceId(\\\"io.dwak.holohackernews.app:id\/action_1\\\").className(\\\"android.widget.Button\\\")\")  File \"\\testcase\\interestcases\\testcase10_1_021.py\", line 34, in getElememt    element = driver.find_element_by_android_uiautomator(str)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 327, in find_element_by_android_uiautomator    return self.find_element(by=By.ANDROID_UIAUTOMATOR, value=uia_string)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 219, in find_element    'value': value})['value']  File \"C:\\Python27\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute    self.error_handler.check_response(response)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 29, in check_response    raise wdeNoSuchElementException: Message: An element could not be located on the page using the given search parameters."},{"firstjacocotime":63.578,"tagname":"10","firstexecutionsuccess":false,"firsttestcasepath":"\\testcase\\interestcases\\testcase11_1_010.py","firstconsumedtime":70.048996,"firstlocpath":"\\exeresult\\interestresult\\11_1_010.txt","firstcoveragepath":"\\coverage\\interestcoverage\\coverage11_1_010.ec","firsterrorlog":"FAILstr(e):\t\t'NoneType' object has no attribute 'click'repr(e):\tAttributeError(\"'NoneType' object has no attribute 'click'\",)Traceback (most recent call last):  File \"\\testcase\\interestcases\\testcase11_1_010.py\", line 111, in <module>    scrollToFindElement(driver, \"new UiSelector().text(\\\"Swipe back to list\\\")\").click()AttributeError: 'NoneType' object has no attribute 'click'FAILstr(e):\t\tMessage: An element could not be located on the page using the given search parameters.repr(e):\tNoSuchElementException()Traceback (most recent call last):  File \"\\testcase\\interestcases\\testcase11_1_010.py\", line 142, in <module>    element = getElememt(driver, \"new UiSelector().resourceId(\\\"io.dwak.holohackernews.app:id\/action_share\\\").className(\\\"android.widget.TextView\\\")\")  File \"\\testcase\\interestcases\\testcase11_1_010.py\", line 34, in getElememt    element = driver.find_element_by_android_uiautomator(str)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 327, in find_element_by_android_uiautomator    return self.find_element(by=By.ANDROID_UIAUTOMATOR, value=uia_string)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 219, in find_element    'value': value})['value']  File \"C:\\Python27\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute    self.error_handler.check_response(response)  File \"C:\\Python27\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 29, in check_response    raise wdeNoSuchElementException: Message: An element could not be located on the page using the given search parameters."}],"interestmap":[]}